#include "platform.h"
#include "xil_printf.h"
#include "xil_cache.h"
#include "xil_types.h"
#include "xparameters.h"
#include "sleep.h"
#include <stdint.h>

#include "xrv32i_pp_ip_mc_gmem.h"
#include "xrv32i_pp_ip_mc_gmem_hw.h"

#include "fruit_small_int8_data.h"
#include "fruit_calibration_scales.h"    /* <--- provides RELU1_OUT_SCALE, RELU2_OUT_SCALE, RELU_FC1_SCALE */


typedef u32 word_type;

#define NB_CORES 4

static const u32 IMEM_BASE[NB_CORES] = {
  0x40000000U, 0x40010000U, 0x40020000U, 0x40030000U
};

#define BRAM_SIZE (64U*1024U)

#define MB_OFS   0x2000U
#define ARR_OFS  0x2100U
#define MB_ADDR(c)   (IMEM_BASE[(c)] + MB_OFS)
#define ARR_ADDR(c)  (IMEM_BASE[(c)] + ARR_OFS)

static inline u32 align_up_u32(u32 x, u32 a){
  u32 m = a - 1U;
  return (x + m) & ~m;
}

static inline int8_t sat_i8_host(int32_t x){
  if(x > 127) return 127;
  if(x < -128) return -128;
  return (int8_t)x;
}

static inline int32_t round_nearest_float_to_int_host(float x){
  return (x >= 0.0f) ? (int32_t)(x + 0.5f) : (int32_t)(x - 0.5f);
}

#define INPUT_C 3
#define INPUT_H 32
#define INPUT_W 32

#define CONV1_OUT_C 8
#define CONV1_OUT_H 32
#define CONV1_OUT_W 32

#define POOL1_OUT_H 16
#define POOL1_OUT_W 16

#define CONV2_OUT_C 16
#define CONV2_OUT_H 16
#define CONV2_OUT_W 16

#define POOL2_OUT_H 8
#define POOL2_OUT_W 8

#define FLAT_SIZE 1024
#define FC1_OUT   32
#define FC2_OUT   5

/* ---------- scales now come from fruit_calibration_scales.h ----------
   RELU1_OUT_SCALE, RELU2_OUT_SCALE, RELU_FC1_SCALE
   are #defined in that header, generated by:
     python calibrate_fruit_int8_scales.py
     python make_fruit_calibration_header.py
   -------------------------------------------------------------------- */

word_type fruit_conv_code_ram_core0[] = {
    #include "fruit_int8_conv_core0.hex"
};
word_type fruit_conv_code_ram_core1[] = {
    #include "fruit_int8_conv_core1.hex"
};
word_type fruit_conv_code_ram_core2[] = {
    #include "fruit_int8_conv_core2.hex"
};
word_type fruit_conv_code_ram_core3[] = {
    #include "fruit_int8_conv_core3.hex"
};

static XRv32i_pp_ip_mc_gmem g[NB_CORES];

static int8_t g_input[INPUT_C * INPUT_H * INPUT_W];
static int8_t g_conv1[CONV1_OUT_C * CONV1_OUT_H * CONV1_OUT_W];
static int8_t g_pool1[CONV1_OUT_C * POOL1_OUT_H * POOL1_OUT_W];
static int8_t g_conv2[CONV2_OUT_C * CONV2_OUT_H * CONV2_OUT_W];
static int8_t g_pool2[CONV2_OUT_C * POOL2_OUT_H * POOL2_OUT_W];
static int8_t g_fc1[FC1_OUT];
static float  g_fc2[FC2_OUT];

static void print_first_i8(const char *name, const int8_t *a, int n, int lim){
  int i;
  xil_printf("%s : ", name);
  for(i = 0; i < n && i < lim; ++i){
    xil_printf("%d ", (int)a[i]);
  }
  xil_printf("\r\n");
}

static void print_first_f(const char *name, const float *a, int n, int lim){
  int i;
  xil_printf("%s : ", name);
  for(i = 0; i < n && i < lim; ++i){
    xil_printf("%d ", (int)(a[i] * 1000.0f));
  }
  xil_printf("\r\n");
}

static void write_imem_words(int cid, const word_type* img, int words){
  u32 base = IMEM_BASE[cid];
  int i;
  for(i = 0; i < words; i++) Xil_Out32(base + (i << 2), img[i]);
}

static int init_core(int cid){
  u16 did = (cid==0)? XPAR_XRV32I_PP_IP_MC_GMEM_0_DEVICE_ID :
            (cid==1)? XPAR_XRV32I_PP_IP_MC_GMEM_1_DEVICE_ID :
            (cid==2)? XPAR_XRV32I_PP_IP_MC_GMEM_2_DEVICE_ID :
                      XPAR_XRV32I_PP_IP_MC_GMEM_3_DEVICE_ID;

  XRv32i_pp_ip_mc_gmem_Config* cfg = XRv32i_pp_ip_mc_gmem_LookupConfig(did);
  if(!cfg) return -1;
  return XRv32i_pp_ip_mc_gmem_CfgInitialize(&g[cid], cfg);
}

static void start_core_with_image(int cid, word_type *img, int words){
  write_imem_words(cid, img, words);
  Xil_DCacheFlushRange(IMEM_BASE[cid], BRAM_SIZE);
  XRv32i_pp_ip_mc_gmem_Set_code_base_words(&g[cid], (u32)(IMEM_BASE[cid] >> 2));
  XRv32i_pp_ip_mc_gmem_Set_ip_num(&g[cid], (u32)cid);
  XRv32i_pp_ip_mc_gmem_Set_start_pc(&g[cid], 0);
  XRv32i_pp_ip_mc_gmem_Set_gmem_offset(&g[cid], 0);
  XRv32i_pp_ip_mc_gmem_Start(&g[cid]);
}

static void load_test_input(void){
  int i;
  for(i = 0; i < INPUT_C * INPUT_H * INPUT_W; ++i){
    g_input[i] = fruit_input_int8[i];
  }
}

static void maxpool2x2_stride2_i8(
  const int8_t *in, int channels, int in_h, int in_w,
  int8_t *out, int out_h, int out_w
){
  int c, oh, ow, kh, kw;
  for(c = 0; c < channels; ++c){
    for(oh = 0; oh < out_h; ++oh){
      for(ow = 0; ow < out_w; ++ow){
        int ih0 = oh * 2;
        int iw0 = ow * 2;
        int8_t maxv = -128;
        for(kh = 0; kh < 2; ++kh){
          for(kw = 0; kw < 2; ++kw){
            int ih = ih0 + kh;
            int iw = iw0 + kw;
            int8_t v = in[c * (in_h * in_w) + ih * in_w + iw];
            if(v > maxv) maxv = v;
          }
        }
        out[c * (out_h * out_w) + oh * out_w + ow] = maxv;
      }
    }
  }
}

static void fc1_host_int8(void){
  int o, i;
  for(o = 0; o < FC1_OUT; ++o){
    int32_t acc = 0;
    float mul_scale = RELU2_OUT_SCALE * fruit_fc1_w_scales[o];

    for(i = 0; i < FLAT_SIZE; ++i){
      acc += ((int32_t)g_pool2[i]) * (int32_t)fruit_fc1_w_int8[o * FLAT_SIZE + i];
    }

    {
      float real_val = ((float)acc) * mul_scale + fruit_fc1_b_float[o];
      int32_t q = round_nearest_float_to_int_host(real_val / RELU_FC1_SCALE);
      if(q < 0) q = 0;
      g_fc1[o] = sat_i8_host(q);
    }
  }
}

static void fc2_host_float(void){
  int o, i;
  for(o = 0; o < FC2_OUT; ++o){
    int32_t acc = 0;
    float mul_scale = RELU_FC1_SCALE * fruit_fc2_w_scales[o];

    for(i = 0; i < FC1_OUT; ++i){
      acc += ((int32_t)g_fc1[i]) * (int32_t)fruit_fc2_w_int8[o * FC1_OUT + i];
    }

    g_fc2[o] = ((float)acc) * mul_scale + fruit_fc2_b_float[o];
  }
}

static void pack_conv_core(
  int cid,
  const int8_t *input, int in_c, int in_h, int in_w,
  const int8_t *weight, const float *bias, const float *w_scales,
  int start_oc, int out_count,
  int out_h, int out_w,
  int input_zero, float input_scale, float output_act_scale
){
  volatile u8 *base = (u8*)ARR_ADDR(cid);

  u32 off_in  = 0;
  u32 off_w   = align_up_u32(off_in + in_c * in_h * in_w, 64);
  u32 off_b   = align_up_u32(off_w + out_count * in_c * 3 * 3, 64);
  u32 off_out = align_up_u32(off_b + out_count * 4u, 64);
  u32 off_ws  = align_up_u32(off_out + out_count * out_h * out_w, 64);
  u32 off_is  = align_up_u32(off_ws + out_count * 4u, 64);
  u32 off_oz  = align_up_u32(off_is + 4u, 64);
  u32 off_os  = align_up_u32(off_oz + out_count * 4u, 64);

  volatile int8_t *arr_in  = (volatile int8_t*)(base + off_in);
  volatile int8_t *arr_w   = (volatile int8_t*)(base + off_w);
  volatile float  *arr_b   = (volatile float *)(base + off_b);
  volatile int8_t *arr_out = (volatile int8_t*)(base + off_out);
  volatile float  *arr_ws  = (volatile float *)(base + off_ws);
  volatile float  *arr_is  = (volatile float *)(base + off_is);
  volatile int32_t *arr_oz = (volatile int32_t*)(base + off_oz);
  volatile float  *arr_os  = (volatile float *)(base + off_os);

  int i;
  for(i = 0; i < in_c * in_h * in_w; ++i) arr_in[i] = input[i];
  for(i = 0; i < out_count * in_c * 3 * 3; ++i)
    arr_w[i] = weight[start_oc * (in_c * 3 * 3) + i];

  for(i = 0; i < out_count; ++i){
    arr_b[i]  = bias[start_oc + i];
    arr_ws[i] = w_scales[start_oc + i];
    arr_oz[i] = 0;
    arr_os[i] = output_act_scale;
  }

  for(i = 0; i < out_count * out_h * out_w; ++i) arr_out[i] = 0;
  arr_is[0] = input_scale;

  {
    volatile u32 *mb = (u32*)MB_ADDR(cid);
    int t;
    for(t = 0; t < 16; ++t) mb[t] = 0;
    mb[8]  = (u32)in_c;
    mb[9]  = (u32)in_h;
    mb[10] = (u32)in_w;
    mb[11] = (u32)out_h;
    mb[12] = (u32)out_w;
    mb[13] = (u32)out_count;
    mb[14] = (u32)input_zero;
  }

  Xil_DCacheFlushRange(IMEM_BASE[cid], BRAM_SIZE);
}

static void run_conv_all(void){
  int c;
  for(c = 0; c < NB_CORES; ++c){
    volatile u32 *mb = (u32*)MB_ADDR(c);
    mb[0] = 0;
    mb[5] = 0;
    Xil_DCacheFlushRange(IMEM_BASE[c], BRAM_SIZE);
  }
  for(c = 0; c < NB_CORES; ++c){
    volatile u32 *mb = (u32*)MB_ADDR(c);
    mb[5] = 1;
    Xil_DCacheFlushRange(IMEM_BASE[c], BRAM_SIZE);
  }
  for(c = 0; c < NB_CORES; ++c){
    volatile u32 *mb = (u32*)MB_ADDR(c);
    while(mb[0] != 1U){
      Xil_DCacheInvalidateRange(IMEM_BASE[c], BRAM_SIZE);
      usleep(1000);
    }
  }
  for(c = 0; c < NB_CORES; ++c){
    volatile u32 *mb = (u32*)MB_ADDR(c);
    mb[5] = 0;
    Xil_DCacheFlushRange(IMEM_BASE[c], BRAM_SIZE);
  }
}

static void gather_conv_outputs_fixedsplit(
  int8_t *dst, int out_h, int out_w, int split_per_core,
  int in_c, int in_h, int in_w
){
  int c;
  for(c = 0; c < NB_CORES; ++c){
    volatile u8 *base = (u8*)ARR_ADDR(c);

    int start_oc = c * split_per_core;
    int out_count = split_per_core;

    u32 off_in  = 0;
    u32 off_w   = align_up_u32(off_in + in_c * in_h * in_w, 64);
    u32 off_b   = align_up_u32(off_w + out_count * in_c * 3u * 3u, 64);
    u32 off_out = align_up_u32(off_b + out_count * 4u, 64);

    const int8_t *src = (const int8_t*)(base + off_out);
    int oc, idx;

    Xil_DCacheInvalidateRange(IMEM_BASE[c], BRAM_SIZE);

    for(oc = 0; oc < out_count; ++oc){
      for(idx = 0; idx < out_h * out_w; ++idx){
        dst[(start_oc + oc) * (out_h * out_w) + idx] =
          src[oc * (out_h * out_w) + idx];
      }
    }
  }
}

static int argmax5_f(const float *a){
  int idx = 0, i;
  for(i = 1; i < 5; ++i){
    if(a[i] > a[idx]) idx = i;
  }
  return idx;
}

int main(void){
  int c;
  int pred;
  static const char *cls[5] = {
    "Apple Red 1", "Banana 1", "Mango 1", "Orange 1", "Pomegranate 1"
  };

  init_platform();
  Xil_DCacheDisable();
  Xil_ICacheDisable();
  xil_printf("\r\n=== Fruit CNN int8 (calibrated scales) ===\r\n");
  xil_printf("RELU1_OUT_SCALE = %d uS\r\n", (int)(RELU1_OUT_SCALE * 1000000.0f));
  xil_printf("RELU2_OUT_SCALE = %d uS\r\n", (int)(RELU2_OUT_SCALE * 1000000.0f));
  xil_printf("RELU_FC1_SCALE  = %d uS\r\n", (int)(RELU_FC1_SCALE * 1000000.0f));

  for(c = 0; c < NB_CORES; ++c){
    if(init_core(c) != 0){
      xil_printf("IP init fail c=%d\r\n", c);
      while(1);
    }
  }

  load_test_input();

  /* ---------------- CONV1 on workers (2 output channels per core) ---------- */
  for(c = 0; c < NB_CORES; ++c){
    start_core_with_image(c,
      (c==0)? fruit_conv_code_ram_core0 :
      (c==1)? fruit_conv_code_ram_core1 :
      (c==2)? fruit_conv_code_ram_core2 :
              fruit_conv_code_ram_core3,
      (c==0)? (int)(sizeof(fruit_conv_code_ram_core0)/4) :
      (c==1)? (int)(sizeof(fruit_conv_code_ram_core1)/4) :
      (c==2)? (int)(sizeof(fruit_conv_code_ram_core2)/4) :
              (int)(sizeof(fruit_conv_code_ram_core3)/4)
    );
    pack_conv_core(
      c, g_input, INPUT_C, INPUT_H, INPUT_W,
      fruit_conv1_w_int8, fruit_conv1_b_float, fruit_conv1_w_scales,
      c * 2, 2, CONV1_OUT_H, CONV1_OUT_W,
      FRUIT_INPUT_ZERO, FRUIT_INPUT_SCALE, RELU1_OUT_SCALE
    );
  }
  run_conv_all();
  gather_conv_outputs_fixedsplit(g_conv1, CONV1_OUT_H, CONV1_OUT_W, 2, INPUT_C, INPUT_H, INPUT_W);

  /* maxpool1 on host */
  maxpool2x2_stride2_i8(g_conv1, CONV1_OUT_C, CONV1_OUT_H, CONV1_OUT_W,
                        g_pool1, POOL1_OUT_H, POOL1_OUT_W);

  /* ---------------- CONV2 on workers (4 output channels per core) ---------- */
  for(c = 0; c < NB_CORES; ++c){
    start_core_with_image(c,
      (c==0)? fruit_conv_code_ram_core0 :
      (c==1)? fruit_conv_code_ram_core1 :
      (c==2)? fruit_conv_code_ram_core2 :
              fruit_conv_code_ram_core3,
      (c==0)? (int)(sizeof(fruit_conv_code_ram_core0)/4) :
      (c==1)? (int)(sizeof(fruit_conv_code_ram_core1)/4) :
      (c==2)? (int)(sizeof(fruit_conv_code_ram_core2)/4) :
              (int)(sizeof(fruit_conv_code_ram_core3)/4)
    );
    pack_conv_core(
      c, g_pool1, CONV1_OUT_C, POOL1_OUT_H, POOL1_OUT_W,
      fruit_conv2_w_int8, fruit_conv2_b_float, fruit_conv2_w_scales,
      c * 4, 4, CONV2_OUT_H, CONV2_OUT_W,
      0, RELU1_OUT_SCALE, RELU2_OUT_SCALE
    );
  }
  run_conv_all();
  gather_conv_outputs_fixedsplit(g_conv2, CONV2_OUT_H, CONV2_OUT_W, 4, CONV1_OUT_C, POOL1_OUT_H, POOL1_OUT_W);

  /* maxpool2 on host */
  maxpool2x2_stride2_i8(g_conv2, CONV2_OUT_C, CONV2_OUT_H, CONV2_OUT_W,
                        g_pool2, POOL2_OUT_H, POOL2_OUT_W);

  /* FC1 on host (int8 -> int8 with ReLU) */
  fc1_host_int8();

  /* FC2 on host (int8 -> float logits) */
  fc2_host_float();

  /* print stage outputs for debugging */
  print_first_i8("conv1_hw", g_conv1, CONV1_OUT_C * CONV1_OUT_H * CONV1_OUT_W, 20);
  print_first_i8("pool1_hw", g_pool1, CONV1_OUT_C * POOL1_OUT_H * POOL1_OUT_W, 20);
  print_first_i8("conv2_hw", g_conv2, CONV2_OUT_C * CONV2_OUT_H * CONV2_OUT_W, 20);
  print_first_i8("pool2_hw", g_pool2, CONV2_OUT_C * POOL2_OUT_H * POOL2_OUT_W, 20);
  print_first_i8("fc1_hw", g_fc1, FC1_OUT, 32);
  print_first_f("fc2_hw", g_fc2, FC2_OUT, 5);

  pred = argmax5_f(g_fc2);
  xil_printf("HW pred : %d\r\n", pred);
  xil_printf("HW cls  : %s\r\n", cls[pred]);

  while(1);
  return 0;
}
